### PR TITLE
updated requests-toolbelt dependency

### LINKED ISSUE #42: Dependency resolution issues with requests-toolbelt 0.9.1
I have a need to use both `dnacentersdk` and `ciscoisesdk` in the same project.    Unfortunately including both projects fails due to dependency resolution on the `requests-toolbelt` package.  

```
  SolverProblemError

  Because no versions of ciscoisesdk match >2.0.8,<3.0.0
   and ciscoisesdk (2.0.8) depends on requests-toolbelt (>=0.9.1,<0.10.0), ciscoisesdk (>=2.0.8,<3.0.0) requires requests-toolbelt (>=0.9.1,<0.10.0).
  And because dnacentersdk (2.5.6) depends on requests-toolbelt (>=0.10.1,<0.11.0)
   and no versions of dnacentersdk match >2.5.6,<3.0.0, ciscoisesdk (>=2.0.8,<3.0.0) is incompatible with dnacentersdk (>=2.5.6,<3.0.0).
  So, because corp-security depends on both dnacentersdk (^2.5.6) and ciscoisesdk (^2.0.8), version solving failed.
```

PR incoming with a change from `0.9.1` to `0.10.1`.

### PR DESCRIPTION
**Pull request by supermanny81**
fixes  #42

### CODE REVIEW

**Comment by steffenschumacher** [comment]
Please prioritise this one - its currently impossible install ciscoisesdk in the same env as ciscodnacentersdk, which is sorta rotten..

**Comment by supermanny81** [comment]
closing since this is no longer needed.

**Comment by oianson** [comment]
> closing since this is no longer needed.

Did you find a workaround or something ..?

**Comment by steffenschumacher** [comment]
They fixed the ise sdk..

**Comment by oianson** [comment]
> They fixed the ise sdk..

Hm, I'm unable to install both SDK's still 

ciscoisesdk==2.0.10
dnacentersdk==2.6.6

The conflict is caused by:
    ciscoisesdk 2.0.10 depends on requests-toolbelt<0.11.0 and >=0.10.1
    dnacentersdk 2.6.6 depends on requests-toolbelt<2.0.0 and >=1.0.0

**Pull request closed without merging**
