### PR TITLE
Partial fix to versioning problem and lint corrections

### PR DESCRIPTION
**Pull request by elear**
This is a partial fix to the versioning problem mentioned in #64.  I have not updated requirements.txt, requirements-dev.txt, or Pipfile[.lock].  This is just about the whl and some linting.

This may or may not test cleanly because the test environment didn't seem to be functioning well.

### CODE REVIEW

**Comment by elear** [comment]
So in other words, don't yet merge without additional testing.

**Comment by oboehmer** [comment]
@elear , do you need any help in getting an ISE to validate this change? This request dependency thing blocks an upgrade we would need in another project ([cisco-internal](https://wwwin-github.cisco.com/AS-Community/CXTA/pull/1599))..

**Comment by oboehmer** [comment]
@bvargasre , any feedback on #64 and Eliot's PR?

**Comment by bvargasre** [comment]
Hi, I will accept the pr, the change will be reflected in pypi when a new tag comes out.

**Pull request merged**
